version: '3.1'
services:
  database:
    image: neo4j
    restart: always
    ports:
    - "7474:7474"
    - "7687:7687"
    environment:
    - NEO4J_AUTH=neo4j/testpwd
  app:
    restart: always
    entrypoint: sh /flight_router/entrypoint.sh
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    links:
      - database
    depends_on:
      - database
    environment:
    - DB_URL=bolt://neo4j:testpwd@database:7687
    ports:
      - "5000:5000"

  app_test:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    links:
      - database
    depends_on:
      - database
    environment:
    - DB_URL=bolt://neo4j:testpwd@database:7687
    ports:
      - "5000:5000"
